name: HAL CI Example
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: git submodule update --init
      - run: make docker-build-and-test
